<?php

/**
 * sfGuardUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserTable extends PluginsfGuardUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUser');
    }
    
    /**
     * Obtiene a un usuario mediante su id de facebook (si es que existe)
     *
     * @param  int  $facebook_id  Id de facebook de un usuario.
     *
     * @return Usuario sfGuardUser que corresponda al facebook_id entregado
     */
    public function getUserByFacebookId($facebook_id)
    {
      $q = $this->createQuery('u')
           ->innerJoin('u.Profile p')
           ->where('p.facebook_uid = ?', $facebook_id);
      
      return $q->fetchOne();
    }
}
