<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version11 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('user_profile', 'facebook_uid', 'string', '20', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('user_profile', 'facebook_uid');
    }
}